name: "Docker Cloud Build"
description: "Builds a docker image using Google Cloud Build and pushes it to Google Container Registry."
author: "Alexander Praschek <alexander.praschek@miragon.io>"
inputs:
  gcp-project-id:
    required: true
    description: >-
      The GCP Project ID to use.
  gcp-service-account-key:
    required: true
    description: >-
      Base64-encoded key file to use to authenticate against Google Cloud Services.
  gcp-cloud-storage-bucket:
    required: false
    description: >-
      Google Cloud Storage Bucket used to temporarily store build input files.
      If not specified, the default value is ${gcp-project-id}_cloudbuild.
  gcp-gcr-region:
    required: false
    description: >-
      The Google Container Registry region to use (gcr.io, us.gcr.io, eu.gcr.io, asia.gcr.io).
      Defaults to eu.gcr.io.
  image-name:
    required: true
    description: >-
      The name of the built image.
  image-sources:
    required: true
    description: >-
      A comma-separated list of files and folders to use as build source. Patterns such as * and ** are supported.
      Paths are relative to the repository root. All matched files and folders are copied to a common directory before
      being passed to Cloud Build.
  image-tag-format:
    required: false
    description: >-
      The format to tag the built image with, if the build was caused by a commit. Builds caused by a tag are always
      labelled with that tag. The format string can contain the following list of parameters. All other parts of the
      string are treated as constants. Make sure you only use characters allowed in a docker tag.
      Defaults to "$BRANCH-$SHA-$YYYY.$MM.$DD-$HH.$mm.$SS", for example "main-4e83ab-2021.04.22-09.08.12".
      Time is based on the server timezone.
      $BRANCH     The branch name, normalized.
      $SHA        The 7-digit SHA of the commit
      $YYYY       The year in 4-digit format
      $MM         The month in 2-digit format
      $DD         The day in 2-digit format
      $HH         The hour in 2-digit format (24h)
      $mm         The minute in 2-digit-format
      $SS         The second in 2-digit-format
  image-tag-latest:
    required: false
    description: >-
      Whether the built image will be tagged with latest. Defaults to false.
  image-tag-branch-latest:
    required: false
    description: >-
      Whether the built image will be tagged with ${branchName}-latest. Defaults to false.
  image-tag-additional-tags:
    required: false
    description: >-
      A comma-separated list of additional tags to use for the built image. Defaults to false.
  github-token:
    required: false
    description: >-
      Token to use to set the commit status. The token is required unless ${github-disabled} is true.
  github-disabled:
    required: false
    description: >-
      Whether to disable all GitHub integrations. Defaults to false.
  github-commit-status-disabled:
    required: false
    description: >-
      Whether to disable setting the commit status to the name and tags of the built docker images. Defaults to false.
  github-commit-status-all:
    required: false
    description: >-
      Whether to put all image tags into separate commit status entry. If false, only the primary tag will be added.
      Defaults to false.
  github-commit-status-description:
    required: false
    description: >-
      The format in which the built images will be displayed. Can be one of the following values. Defaults to small.
      - large     host/project/image:tag    eu.gcr.io/flowsquad-io/test-image:latest
      - medium    project/image:tag         flowsquad-io/test-image:latest
      - small     image:tag                 test-image:latest
      - tiny      tag                       latest
  github-commit-status-title:
    required: false
    description: >-
      The title to use for the commit status. Will be suffixed with an index when github-commit-status-all is true.
      Defaults to "Docker Image".
  github-release-information-disabled:
    required: false
    description: >-
      Whether to disable updating the release information with the built docker images. Defaults to false.
  github-release-information-all:
    required: false
    description: >-
      Whether to add all built image tags to the list of images. Else only the image tagged with the release tag will
      be added. Defaults to false.
outputs:
  full-image-name:
    description: >-
      Contains the full image name with host, project ID and image name without tags.
  image-tags:
    description: >-
      Contains a comma-separated list of tags for the built image.
runs:
  using: "node18"
  main: "dist/index.js"
branding:
  color: "blue"
  icon: "package"
